import Head from "next/head";
import { SubmitHandler, useForm } from "react-hook-form";
import A from "@/components/parts/A";
import ActionButton from "@/components/parts/ActionButton";
import CancelButton from "@/components/parts/CancelButton";
import Input from "@/components/parts/Input";
import Label from "@/components/parts/Label";
import Li from "@/components/parts/Li";
import Select from "@/components/parts/Select";
import Title from "@/components/parts/Title";
import Ul from "@/components/parts/Ul";
import { FieldWrapper } from "@/components/templates/FieldWrapper";

type Inputs = {
  label1: string;
  label2: string;
  select: string;
};

export default function Home() {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = (data) => {
    console.log(data);
    alert("submit!");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="container mx-auto space-y-2 py-2">
            <Title>Title</Title>
            <div className="flex flex-col gap-2 md:flex-row">
              <FieldWrapper
                className="basis-1/2"
                label="label1"
                error={errors.label1}
              >
                <Input {...register("label1", { required: "必須です" })} />
              </FieldWrapper>
              <FieldWrapper
                className="basis-1/4"
                label="label2"
                error={errors.label2}
              >
                <Input
                  {...register("label2", {
                    maxLength: {
                      value: 5,
                      message: "5桁以内で入力してください",
                    },
                  })}
                />
              </FieldWrapper>
              <FieldWrapper
                className="basis-1/4"
                label="Select"
                error={errors.select}
              >
                <Select {...register("select", { required: "必須です" })}>
                  <option value="">選択してください</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </Select>
              </FieldWrapper>
            </div>
            <div>
              <A href="#">link</A>
            </div>
            <div>
              <Label>List</Label>
              <Ul>
                <Li>Value1</Li>
                <Li>Value2</Li>
                <Li>Value3</Li>
              </Ul>
            </div>
          </div>
          <div className="mt-8 flex justify-center gap-2">
            <CancelButton>Cancel</CancelButton>
            <ActionButton type="submit">Action</ActionButton>
          </div>
        </form>
      </main>
    </>
  );
}
